SRC = '../cpp/src';
INC = '../cpp/include';

disp('Running >> mex mexGPisMap.cpp covFnc.cpp ObsGP.cpp OnGPIS.cpp strct.cpp quadtree.cpp octree.cpp GPisMap.cpp...');
mex('mexGPisMap3.cpp',strcat(SRC,'/covFnc.cpp'),strcat(SRC,'/ObsGP.cpp'),strcat(SRC,'/OnGPIS.cpp'),...
    strcat(SRC,'/strct.cpp'),strcat(SRC,'/octree.cpp'),...
    strcat(SRC,'/GPisMap3.cpp'),...
    strcat('-I',INC),'-I/usr/local','-I/usr/include/eigen3','CXXFLAGS=-std=c++11 -pthread -fPIC','-O'); % 
